stages:
  split:
    cmd: python src/data/split_data.py
    deps:
    - https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  normalize:
    cmd: python src/data/normalization_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalization_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/data/grid_search_data.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/data/grid_search_data.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/data/model_train_data.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/data/model_train_data.py
    outs:
    - models/trained_model.pkl
  evaluate:
    cmd: python src/data/evaluation_data.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/trained_model.pkl
    - src/data/evaluation_data.py
    outs:
    - models/predictions.csv
    metrics:
    - metrics/scores.json
