stages:
  split:
    cmd: python src/data/split_data.py
    deps:
    - /home/ubuntu/exam_dvc/raw_data/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  normalize:
    cmd: python src/data/normalization_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalization_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/data/grid_search_data.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/y_train.csv
    - src/data/grid_search_data.py
    outs:
    - models/best_params.pkl
